version: '3'

services:
  server:
    image: nginx
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/conf.d/default.conf"
      - "./php:/var/www/html"
    ports:
      - "8080:80"
    depends_on:
      - php
  db:
    image: mysql:5.7
    environment:
     MYSQL_ROOT_PASSWORD: root
     MYSQL_DATABASE: test_db
     MYSQL_USER: docker
     MYSQL_PASSWORD: docker
     TZ: 'Asia/Tokyo'
    
    ports:
      - "3306:3306"
  php:
    build: ./php
    volumes:
      - "./php:/var/www/html"
    depends_on:
      - db
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_USER: root
      PMA_PASSWORD: root
    ports:
      - "8888:80"
    depends_on:
      - db
